# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: sha512
            encode_as_base64: false
            iterations: 1
        Nestle\CoreBundle\Model\NestleUsers: plaintext

    role_hierarchy:
        ROLE_ANALYST:     ROLE_USER
        ROLE_ADMIN:       [ ROLE_ANALYST, ROLE_ALLOWED_TO_SWITCH ]

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        chain_provider:
            chain:
                providers: [ in_memory, bower_user ]
        in_memory:
            memory:
                users:
                    superadmin: { password: 9e54894425aee8a4e5c22a760358807534409594cf99bf4cc988735634cf0decb9f7bb4200d58d16c286ad1b82afd716e64d32578fa93848e8e000a1d126dab8, roles: [ 'ROLE_ADMIN' ] }
        bower_user:
            propel:
                class: Nestle\CoreBundle\Model\NestleUsers
                property: username

    access_denied_url: error403

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false

        mobile:
            pattern:  ^/mobile$
            security: false

        secured_area:
            provider: chain_provider
            pattern: ^/
            form_login:
                check_path: _security_check
                login_path: login
                default_target_path: /
                use_forward: true
                use_referer: true
                success_handler: login_handler
            logout:
                path: logout
                target: login
                success_handler: logout_handler
            anonymous: ~

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/error404, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/error403, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/mobile, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_ANALYST }

        #main:
            #anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
